export enum ConfigKey {
    PORT = 'PORT',
    API_PREFIX = 'API_PREFIX',

    SEQUELIZE_DATABASE_DIALECT = 'SEQUELIZE_DATABASE_DIALECT',
    SEQUELIZE_DATABASE_HOST = 'SEQUELIZE_DATABASE_HOST',
    SEQUELIZE_DATABASE_PORT = 'SEQUELIZE_DATABASE_PORT',
    SEQUELIZE_DATABASE_USERNAME = 'SEQUELIZE_DATABASE_USERNAME',
    SEQUELIZE_DATABASE_PASSWORD = 'SEQUELIZE_DATABASE_PASSWORD',
    SEQUELIZE_DATABASE_NAME = 'SEQUELIZE_DATABASE_NAME',

    JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
    JWT_ACCESS_TOKEN_EXPIRES_TIME = 'JWT_ACCESS_TOKEN_EXPIRES_TIME',
}
